[[services]]
name = "web"

[services.build]
buildCommand = "npm ci && npm run build"

[services.deploy]
startCommand = "npm run start"

[[services]]
name = "storybook"

[services.build]
dockerfilePath = "storybook.Dockerfile"
