[[services]]
name = "web"

[services.build]
buildCommand = "npm ci && npm run build"

[services.deploy]
startCommand = "npm run start"

[[services]]
name = "workers"

[services.build]
buildCommand = "npm ci"

[services.deploy]
startCommand = "npm run start:workers"

[[services]]
name = "storybook"

[services.build]
buildCommand = "npm ci && npm run build-storybook"

[services.deploy]
startCommand = "npm run start:storybook"